version: '2'

services:
  db:
    image: 'postgres:15.2-alpine'
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pwd
volumes:
  db-data: